# Generated by Django 5.1.5 on 2025-02-01 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca2', models.CharField(max_length=2)),
                ('cca3', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('subregion', models.CharField(max_length=255)),
                ('miembroUE', models.BooleanField()),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frontera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca3_frontera', models.CharField(max_length=3)),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperaturas_app.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperatura', models.FloatField()),
                ('sensacion', models.FloatField()),
                ('minima', models.FloatField()),
                ('maxima', models.FloatField()),
                ('humedad', models.FloatField()),
                ('amanecer', models.TimeField()),
                ('atardecer', models.TimeField()),
                ('idpais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temperaturas_app.pais')),
            ],
        ),
    ]
